"""snapshot

Revision ID: 2b5f38f736ed
Revises: b46897eb75f8
Create Date: 2021-01-16 02:22:03.191448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b5f38f736ed'
down_revision = 'b46897eb75f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('creatures', sa.Column('notes', sa.String(), nullable=True))
    op.add_column('genuses', sa.Column('notes', sa.String(), nullable=True))
    op.drop_index('printer_statuses_timestamp_idx', table_name='printer_statuses')
    op.add_column('species', sa.Column('notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('species', 'notes')
    op.create_index('printer_statuses_timestamp_idx', 'printer_statuses', ['timestamp'], unique=False)
    op.drop_column('genuses', 'notes')
    op.drop_column('creatures', 'notes')
    # ### end Alembic commands ###
